#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Author: Chmouel Boudjnah <chmouel@chmouel.com>
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
import argparse
import configparser
import os
import readline
import subprocess
import sys
import tempfile

import iterfzf
import jira

readline.parse_and_bind("tab: complete")

RESTRICT_ISSUE_TYPE = [
    'Bug', 'Feature Request', 'Enhancement', 'Task', 'Epic', 'Story'
]


class JIC(object):
    def __init__(self, args):
        self._cnx = False
        self.args = args
        self.config = None

    def set_config(self):
        username = os.environ.get("JIRA_USERNAME")
        password = os.environ.get("JIRA_PASSWORD")
        server = os.environ.get("JIRA_SERVER")
        if username and password and server:
            return {
                'username': username,
                'password': password,
                'server': server,
            }
        configfile = os.path.expanduser("~/.config/jira.ini")
        if not os.path.exists(configfile):
            raise Exception("No configuration file has been set")
        config = configparser.ConfigParser()
        config.read(configfile)
        self.config = {
            "server": config.get('jira', 'server'),
            "username": config.get('jira', 'username'),
            "password": config.get('jira', 'password')
        }

    def inputstring(self, prompt):
        return input(prompt)

    def edit(self):
        tmpfile = tempfile.mkstemp(".md", "jira-issue-create-")[1]
        if self.args.editor:
            editor = self.args.editor
        elif 'EDITOR' in os.environ:
            editor = os.environ['EDITOR']
        else:
            editor = 'vi'
        editor = editor.split(" ")
        editor.append(tmpfile)
        subprocess.call([editor[0], *editor[1:]])
        blob = open(tmpfile, 'r').readlines()
        os.remove(tmpfile)
        return blob

    def get_cnx(self):
        if self._cnx:
            return self._cnx
        self._cnx = jira.JIRA(
            server=self.config['server'],
            basic_auth=(self.config['username'], self.config['password']))
        return self._cnx

    # Not using the whole list if issue_type and only a static list cause a lot
    # of irrelevant stuff in there,
    def get_issuetype(self):
        return iterfzf.iterfzf(RESTRICT_ISSUE_TYPE, prompt="Issue Type> ")

    def _get(
            self,
            func,
            *args,
            prompt="",
    ):
        prompt += "> "
        objs = func(*args)
        oname = iterfzf.iterfzf(
            reversed(sorted([ob.name for ob in objs])), prompt=prompt)
        if not oname:
            raise Exception("You need to choose a " + prompt)
        return [o for o in objs if o.name == oname][0]

    def get_project(self):
        cnx = self.get_cnx()
        return self._get(cnx.projects, prompt="Project")

    def get_priorities(self):
        cnx = self.get_cnx()
        return self._get(cnx.priorities, prompt="Priority")

    def get_component(self, project):
        cnx = self.get_cnx()
        return self._get(cnx.project_components, project, prompt="Component")

    def get_versions(self, project):
        cnx = self.get_cnx()
        return self._get(cnx.project_versions, project, prompt="Version")

    def issue(self):
        self.set_config()

        cnx = self.get_cnx()
        summary = self.inputstring("Enter a title for your issue: ")
        project = self.get_project()
        issuetype = self.get_issuetype()
        component = self.get_component(project)
        version = self.get_versions(project)
        priority = self.get_priorities()

        assign = self.inputstring("Enter an assignee ('me' for yourself): ")
        print("Launching your editor to edit the description of the issue.")
        description = self.edit()

        if assign == 'me':
            assignee = {'name': self.config['username']}

        dico = {
            'project': project,
            'summary': summary,
            'description': description,
            'issuetype': {
                'name': issuetype
            },
            'assignee': assignee,
            'components': [{
                'name': component
            }],
            'versions': [{
                'name': version
            }],
            'priority': {
                'name': priority
            }
        }

        if self.args.test:
            print(dico)
        else:
            created = cnx.create_issue(**dico)
            print(created.permalink())


def launch(args=None):
    parser = argparse.ArgumentParser(description='Create a JIRA issue.')
    parser.add_argument(
        "--editor", type=str, help="Editor to use default to $EDITOR or vim.")
    parser.add_argument(
        "-t", "--test", default=False, action='store_true', help="Test mode")

    args = parser.parse_args(args or sys.argv[1:])
    m = JIC(args)
    m.issue()


if __name__ == '__main__':
    launch()
